name: Auto Version Bump and Tag

on:
  push:
    branches:
      - main

jobs:
  versioning:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4
      
      # Step 2: Configure Git user for automation
      - name: Configure Git user for automation
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      # Step 2: Set up Node.js environment
      # Required for Vite, npm, and semantic-release to work
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20  # Use latest LTS version

      # Step 3: Install project dependencies using npm
      - name: Install dependencies
        run: npm ci  # Faster and reproducible install based on package-lock.json

      # Step 4: (Optional) Build your project
      # This ensures the app builds without errors before tagging a release
      - name: Build project
        run: npm run build

      # Step 5: Run semantic-release to:
      # - Analyze commits
      # - Determine next version (based on commit type)
      # - Update package.json and CHANGELOG.md
      # - Create a new Git tag
      # - Publish a GitHub Release
      - name: Run Semantic Release
        env:
          GH_TOKEN: ${{ secrets.Personal_TOKEN }}  # GitHub token to push tags and create release
        run: npx semantic-release
